theme: jekyll-theme-slate
//title: varianapis.github.io
description: This open source community project supports Varian collaborators and customers in their work with Varian Medical Systems public APIs. Replacement for CodePlex.
github:
  repository_url: https://github.com/VarianAPIs
